### ISSUE TITLE
Python3 random client fails

### ISSUE THREAD

**Issue by grepsr** [wuyunfeng/Python-FastCGI-Client#1]
When I try to use this with Python3, it works but it fails many times randomly.

The issue seems to be, the request body seems to be 10-15 bytes longer when it fails. This is very consistent.

This seems to work much better, when I get smaller random number of requestId, by doing the following. But I don't thing this is a good fix. Is there a proper fix for this?

```requestId = random.randint(1, 50)```

**Comment by grepsr** [comment]
Here's my edited version for this:
https://gist.github.com/grepsr/66e5fb5271a6db4826b2ea5d352dd4c8

**Comment by wuyunfeng** [comment]
I need find a Python3 version enviroment to make some test. @grepsr

**Comment by grepsr** [comment]
@wuyunfeng thanks, please use my gist above, I've made the code compatible with python3.

Just that one random bug exists at the moment.

**Comment by wuyunfeng** [comment]
@grepsr can you give me your error message???

**Comment by grepsr** [comment]
@wuyunfeng there is no error message, it simply just fails. 

In the gist below, it goes to line 107 and the header is empty - so it returns False and quits.
https://gist.github.com/grepsr/66e5fb5271a6db4826b2ea5d352dd4c8

**Comment by wuyunfeng** [comment]
@grepsr  try change chr((requestid >> 8) & 0xFF)  to chr((requestid >> 8) & 0x000000FF)  and chr(requestid & 0x000000FF)  on line 68,69 ?

**Comment by grepsr** [comment]
I will try and let you know, thanks!

**Comment by grepsr** [comment]
That does not work unfortunately..

The only way it works consistently now is, if change the requestId code to:
requestId = random.randint(1, 10)

But a random of 1 to 10 is pretty small - and I'm worried it might conflict.

**Comment by wuyunfeng** [comment]
@grepsr Are you sure you run this on Python3 ?   python3 does not support `from urlparse import urlparse as parse_url`, python3 had merged this API into `urllib`.

**Comment by wuyunfeng** [comment]
@grepsr Are you sure you run this on Python3 ?  I can not run this project on python3. Some API are different from python2

**Comment by grepsr** [comment]
@wuyunfeng Yes, it works on python3 after changing a few things (I used 2to3 conversion tool) - https://docs.python.org/2/library/2to3.html

The only issue seems to be due to the random request number.

**Comment by wuyunfeng** [comment]
@grepsr  OK... maybe this bug produced by the transformation from 2 to 3. Are you trying write a python3 version directly?
