### ISSUE TITLE
发起一个请求时，怎样增加headers参数

### ISSUE THREAD

**Issue by guodong-xia** [wuyunfeng/Python-FastCGI-Client#3]

**Comment by wuyunfeng** [comment]
params里面可以添加的，看readme那个例子有

**Comment by guodong-xia** [comment]
你好：
很高兴您能回复，就您的回复我想确认一下；
假如请求一个接口，需要在请求的Headers中添加参数（x-user-id：123），是如图这样添加吗？





------------------ 原始邮件 ------------------
发件人: "Yunfeng,Wu"<notifications@github.com>;
发送时间: 2019年9月2日(星期一) 晚上7:51
收件人: "wuyunfeng/Python-FastCGI-Client"<Python-FastCGI-Client@noreply.github.com>;
抄送: "夏国栋"<guodong_xia@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wuyunfeng/Python-FastCGI-Client] 发起一个请求时，怎样增加headers参数 (#3)




params里面可以添加的，看readme那个例子有

**Comment by wuyunfeng** [comment]
我看不见图呀

**Comment by wuyunfeng** [comment]
params = {'GATEWAY_INTERFACE': 'FastCGI/1.0',
      'REQUEST_METHOD': 'POST',
      'SCRIPT_FILENAME': documentRoot + uri,
      'SCRIPT_NAME': uri,
      'QUERY_STRING': '',
      'REQUEST_URI': uri,
      'DOCUMENT_ROOT': documentRoot,
      'SERVER_SOFTWARE': 'php/fcgiclient',
      'REMOTE_ADDR': '127.0.0.1',
      'REMOTE_PORT': '9985',
      'SERVER_ADDR': '127.0.0.1',
      'SERVER_PORT': '80',
      'SERVER_NAME': "localhost",
      'SERVER_PROTOCOL': 'HTTP/1.1',
      'CONTENT_TYPE': 'application/x-www-form-urlencoded',
      'CONTENT_LENGTH': len(content),
       **'x-user-id' : 123**
      }

**Comment by wuyunfeng** [comment]
@guodong-xia 你试试

**Comment by guodong-xia** [comment]
我试过了，还是获取不到这个头参数




------------------ 原始邮件 ------------------
发件人: "Yunfeng,Wu"<notifications@github.com>;
发送时间: 2019年9月2日(星期一) 晚上8:53
收件人: "wuyunfeng/Python-FastCGI-Client"<Python-FastCGI-Client@noreply.github.com>;
抄送: "夏国栋"<guodong_xia@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [wuyunfeng/Python-FastCGI-Client] 发起一个请求时，怎样增加headers参数 (#3)




@guodong-xia 你试试

**Comment by wuyunfeng** [comment]
不应该的呀，里面的参数都会发过去的，'123', 你在PHP那一端是怎么获取的 贴出来看看，另外你check下其他参数是否能拿到

**Comment by guodong-xia** [comment]
加引号我也试过了，但接口确实收不到header头的这个参数


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Yunfeng,Wu <notifications@github.com&gt;
发送时间: 2019年9月2日 21:26
收件人: wuyunfeng/Python-FastCGI-Client <Python-FastCGI-Client@noreply.github.com&gt;
抄送: 夏国栋 <guodong_xia@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[wuyunfeng/Python-FastCGI-Client] 发起一个请求时，怎样增加headers参数 (#3)




不应该的呀，里面的参数都会发过去的，'123'

**Comment by wuyunfeng** [comment]
你把你怎么拿header发出来呀

**Comment by guodong-xia** [comment]
好的，我是测试人员，具体接口那边怎么拿header的也不是太清楚，我先尝试看看接口代码


------------------ 原始邮件 ------------------
发件人: Yunfeng,Wu <notifications@github.com&gt;
发送时间: 2019年9月3日 10:32
收件人: wuyunfeng/Python-FastCGI-Client <Python-FastCGI-Client@noreply.github.com&gt;
抄送: 夏国栋 <guodong_xia@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[wuyunfeng/Python-FastCGI-Client] 发起一个请求时，怎样增加headers参数 (#3)




你把你怎么拿header发出来呀

**Comment by wuyunfeng** [comment]
是有人负责开发吗？

**Comment by guodong-xia** [comment]
嗯，是的，我这边要做的是用fcgi-client去调用接口做自动化测试




------------------ 原始邮件 ------------------
发件人: "Yunfeng,Wu"<notifications@github.com>;
发送时间: 2019年9月3日(星期二) 上午10:36
收件人: "wuyunfeng/Python-FastCGI-Client"<Python-FastCGI-Client@noreply.github.com>;
抄送: "夏国栋"<guodong_xia@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [wuyunfeng/Python-FastCGI-Client] 发起一个请求时，怎样增加headers参数 (#3)




是有人负责开发吗？

**Comment by wuyunfeng** [comment]
你需要确定下服务端是怎么拿到header参数的

**Comment by guodong-xia** [comment]
嗯，好的，我这边有用postman测试过，直接在Headers里面加参数，接口能正常获取到参数。




------------------ 原始邮件 ------------------
发件人: "Yunfeng,Wu"<notifications@github.com>;
发送时间: 2019年9月3日(星期二) 上午10:41
收件人: "wuyunfeng/Python-FastCGI-Client"<Python-FastCGI-Client@noreply.github.com>;
抄送: "夏国栋"<guodong_xia@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [wuyunfeng/Python-FastCGI-Client] 发起一个请求时，怎样增加headers参数 (#3)




你需要确定下服务端是怎么拿到header参数的

**Comment by wuyunfeng** [comment]
这个client是严格按照fastcgi协议进行转换的

**Comment by wuyunfeng** [comment]
__encodeNameValueParams 这个函数是负责传header的

http://www.mit.edu/~yandros/doc/specs/fcgi-spec.html#S3.4
Name-Value Pairs

**Comment by guodong-xia** [comment]
你好：


之前的问题已经解决了；
我在阅读接口源码发现接口在提取header参数时，会先判断参数的key是不是以‘HTTP_’开头的，
所以我就怀疑在发起http请求时，是不是会给header参数的key自动加上‘HTTP_’，后来通过加
日志，证实了这个猜测。所以我在使用fcgi_client传递header参数时，加上‘HTTP_’后就能正常
返回了，如下：
params = {'GATEWAY_INTERFACE': 'FastCGI/1.0',
          'REQUEST_METHOD': method,
          'SCRIPT_FILENAME': self.script_file,
          'SCRIPT_NAME': uri,
          'QUERY_STRING': str(req),
          'REQUEST_URI': uri,
          'DOCUMENT_ROOT': '',
          'SERVER_SOFTWARE': 'php/fcgiclient',
          'REMOTE_ADDR': '127.0.0.1',
          'REMOTE_PORT': '9985',
          'SERVER_ADDR': '127.0.0.1',
          'SERVER_PORT': '80',
          'SERVER_NAME': "localhost",
          'SERVER_PROTOCOL': 'HTTP/1.1',
          'CONTENT_TYPE': 'application/x-www-form-urlencoded',
          'DOCUMENT_URI': uri,
          'CONTENT_LENGTH': len(content),
          'HTTP_x_user_id': 123
          }
最后，感谢您这么多的邮件回复和帮助，谢谢了！




------------------ 原始邮件 ------------------
发件人: "Yunfeng,Wu"<notifications@github.com>;
发送时间: 2019年9月3日(星期二) 上午10:46
收件人: "wuyunfeng/Python-FastCGI-Client"<Python-FastCGI-Client@noreply.github.com>;
抄送: "夏国栋"<guodong_xia@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [wuyunfeng/Python-FastCGI-Client] 发起一个请求时，怎样增加headers参数 (#3)




__encodeNameValueParams 这个函数是负责传header的

**Comment by wuyunfeng** [comment]
好的

发自我的 iPhone

**Comment by wuyunfeng** [comment]
以HTTP开头的应该是你们自己业务加的吧

**Comment by guodong-xia** [comment]
不是，应该是http协议规范的吧，自定义的header都是使用HTTP_作为前缀


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Yunfeng,Wu <notifications@github.com&gt;
发送时间: 2019年9月3日 18:25
收件人: wuyunfeng/Python-FastCGI-Client <Python-FastCGI-Client@noreply.github.com&gt;
抄送: 夏国栋 <guodong_xia@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[wuyunfeng/Python-FastCGI-Client] 发起一个请求时，怎样增加headers参数 (#3)




以HTTP开头的应该是你们自己业务加的吧
